import * as images from './index'; // Import all images from index.ts

const assets = [
    { name: 'AWS', path: images.aws },
    { name: 'Docker', path: images.docker },
    { name: 'Git', path: images.git },
    { name: 'GitHub', path: images.github },
    { name: 'GitLab', path: images.gitlab },
    { name: 'JavaScript', path: images.js },
    { name: 'Node', path: images.node },
    { name: 'Express', path: images.express },
    { name: 'Figma', path: images.figma },
    { name: 'Sass', path: images.sass },
    { name: 'MySQL', path: images.mysql },
    { name: 'Next.js', path: images.next },
    { name: 'React', path: images.react },
    { name: 'Socket.io', path: images.socketio },
    { name: 'MongoDB', path: images.mongodb },
    { name: 'PostgreSQL', path: images.postgresql },
    { name: 'Prisma', path: images.prisma },
    { name: 'TypeScript', path: images.typescript },
    { name: 'Tailwind CSS', path: images.tailwind },
    { name: 'VSCode', path: images.vscode },
    { name: 'Redux', path: images.redux },
    { name: 'Vite', path: images.vite },
    { name: 'ShadCN', path: images.shadcn },
    { name: 'Three.js', path: images.threejs },
    { name: 'GSAP', path: images.gsap },
    { name: 'Firebase', path: images.firebase },
    { name: 'Cloudinary', path: images.cloudinary },
    { name: 'React Query', path: images.reactQuery },
    { name: 'Zod', path: images.zod },
    { name: 'AG Grid', path: images.aggrid },
    { name: 'GraphQL', path: images.graphql },
    { name: 'Apollo', path: images.apollo },
    { name: 'Framer Motion', path: images.framermotion },
    { name: 'Auth0', path: images.autho },
    { name: 'NextAuth', path: images.nextAuth },
    { name: 'Expo', path: images.expo },
    { name: 'Gemini', path: images.gemini },
    { name: 'OpenAI', path: images.openai },
    { name: 'Vercel', path: images.vercel },
    { name: 'React Router', path: images.reactRouter },
    { name: 'Notion', path: images.notion },
    { name: 'JSON', path: images.json }
];

export default assets; // Export the assets array